---
- hosts: test
  become: true
  tasks:
  #  - name: install 
  #    yum: name="{{item}}" state=present
  #    loop:
  #     - php
  #     - mariadb

   - name: install dev tools
     yum: name="@Development tools" state=present
    #  when: ansible_hostname in groups['dev']
  #  - name: update
  #    yum: name="*" state=latest
  #    when: ansible_hostname in groups['dev']
