---
- hosts: test
  tasks:
    - name: install http
      yum: name="{{item}}" state=present
      loop:
        - httpd
        - firewalld

    - name: svc
      service: name=httpd state=started enabled=true
    - name: svc-fire
      firewalld: service=http state=enabled permanent=true immediate=true
    - name: group
      group: name=webdev state=present
    - name: dir
      file: path=/webdev state=directory group=webdev mode="2775" setype=httpd_sys_content_t
    - name: sym
      file: src=/webdev dest=/var/www/html/webdev state=link
    - name: content
      copy: content="devops\n" dest=/webdev/index.html setype=httpd_sys_content_t
