---
- hosts: all
  become: true
  tasks:
   - name: template
     template: src=./templates/hosts.j2 dest=/etc/hosts
     when: inventory_hostname in groups['dev'] or inventory_hostname in groups['test']
