---
   - name: install
     yum: name=httpd state=present 
   - name: svc
     service: name=httpd state=started enabled=true
   - name: index
     template: src=index.html.j2 dest=/var/www/html/index.html
     notify: restart httpd
   - name: fire
     firewalld: service=http state=enabled permanent=true immediate=true
  

