---
- hosts: dev
  tasks:
    - name: install
      yum: name="{{item}}" state=present
      loop:
        - httpd
        - firewalld
    - name: svc
      service: name="{{item}}" state=started enabled=true
      loop:
        - httpd
        - firewalld
    - name: port
      firewalld: service=http state=enabled immediate=true permanent=true
    - name: group
      group: name=webdev state=present
    - name: dir
      file: path=/webdev state=directory group=webdev mode="2775" 
    - name: link
      file: src=/webdev dest=/var/www/html/webdev state=link
    - name: content
      copy: content="Development!\n" dest=/webdev/index.html
    - name: semanage
      sefcontext:  target='/webdev(/.*)?' setype="httpd_sys_content_t" state=present
      notify: restore context

  handlers:
    - name: restore context
      command: restorecon -irv /webdev
