---
- hosts: test,dev
  tasks:
   - name: install
     yum: name+"{{item}}" state=present
     loop:
      - php
      - mariadb
   - name: develop 
     yum: name="@Development tools" state=present
     when: ansible_hostname in groups['test']
   - name: update
     yum: name="*" state=latest
     when: ansible_hostname in groups['test']

