---
- hosts: test
  tasks:
   - name: install
     yum: name=httpd state=present
   - name: svc
     service: name="{{item}}" state=started enabled=true
     loop:
      - httpd
      - firewalld
   - name: firewall
     firewalld: service=http state=enabled immediate=true permanent=true
   - name: config
     template: src=templates/index.j2 dest=/var/www/html/index.html
     notify: restart httpd

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted enabled=true

   
