---
- hosts: test 
  become: true 
  tasks:
    - name: cron job 
      # cron: name=uptime minute="*/15" hour="8-23" day="1-5" user=chris job="uptime >> /home/chris/cron_txt" cron_file="uptime"
      cron: name=uptime minute="*/2" user=root job="uptime >> /root/cron.job" cron_file="uptime"