---
- hosts: all
  vars:
    timesync_ntp_servers:
      - hostname: 2.pool.ntp.org
        iburst: yes
      - hostname: 1.pool.ntp.org
        iburst: yes
  roles:
    - rhel-system-roles.timesync

