---
- hosts: prod
  tasks:
    - name: install 
      yum: name="{{item}}" state=present
      loop:
        - httpd
        - firewalld
    - name: svc
      service: name="{{item}}" state=started enabled=true
      loop:
        - httpd
        - firewalld
    - name: port
      firewalld: service=http state=enabled permanent=true immediate=true
    - name: group
      group: name=webdev state=present
    - name: dir
      file: path=/webdev state=directory mode='2775' setype=httpd_sys_content_t
    - name: symlink
      file: src=/webdev dest=/var/www/html/webdev state=link
    - name: copy content
      copy: content="prod web\n" dest=/webdev/index.html setype=httpd_sys_content_t
