---
- hosts: database
  become: true
  remote_user: root
  tasks:
   - name: install
     yum: name=lvm2 state=latest
   - name: get info
     parted: device=/dev/sdb unit=GiB
     register: sdb_info
   - debug: msg={{sdb_info}}
   - parted: device=/dev/sdb number=2 flags="[lvm]" state=present part_type=primary part_start="{{sdb_info.partitions[0].end + 1}}MiB" part_end="{{sdb_info.partitions[0].end + 2048}}MiB" unit=MiB